#!/usr/bin/env bash

# CC Wrapper - Source this in your shell to use 'cc' command
# This file is auto-generated by MCM

export MCM_DIR="${MCM_DIR:-$HOME/.mcm}"
export CCWRAP_MARKER="# MCM CC Wrapper"

_ccwrap_load_config() {
    local config_file="$MCM_DIR/config.json"
    if [[ -f "$config_file" ]]; then
        export CURRENT_PROVIDER=$(python3 -c "
import json
with open('$config_file') as f:
    print(json.load(f).get('current', 'none'))
" 2>/dev/null || echo "none")
    else
        export CURRENT_PROVIDER="none"
    fi
}

_ccwrap_load_provider_config() {
    local provider="$1"
    local keys_file="$MCM_DIR/.keys.enc"
    local key_file="$MCM_DIR/.key"
    local providers_file="$MCM_DIR/providers.json"
    
    if [[ ! -f "$key_file" || ! -f "$keys_file" ]]; then
        return 1
    fi
    
    local key=$(cat "$key_file")
    
    local api_key=$(openssl enc -aes-256-cbc -A -a -d -pbkdf2 -pass "pass:$key" -in "$keys_file" 2>/dev/null | \
        python3 -c "import json,sys; print(json.load(sys.stdin).get('$provider', ''))" 2>/dev/null || echo "")
    
    if [[ -z "$api_key" ]]; then
        return 1
    fi
    
    local provider_info=$(cat "$providers_file" 2>/dev/null | python3 -c "
import json, sys
data = json.load(sys.stdin)
for p in data.get('providers', []):
    if p['id'] == '$provider':
        print(json.dumps(p))
        break
" 2>/dev/null || echo "")
    
    if [[ -z "$provider_info" ]]; then
        return 1
    fi
    
    local base_url=$(echo "$provider_info" | python3 -c "import json,sys; print(json.load(sys.stdin).get('base_url', ''))")
    local api_key_var=$(echo "$provider_info" | python3 -c "import json,sys; print(json.load(sys.stdin).get('api_key_var', ''))")
    local env_vars_json=$(echo "$provider_info" | python3 -c "import json,sys; print(json.dumps(json.load(sys.stdin).get('env_vars', {})))")
    
    unset ANTHROPIC_API_KEY
    export ANTHROPIC_BASE_URL="$base_url"
    export ANTHROPIC_AUTH_TOKEN="$api_key"
    
    echo "$env_vars_json" | python3 -c "
import json, sys
for key, value in json.load(sys.stdin).items():
    print(f'export {key}=\"{value}\"')
" | while read -r line; do
        eval "$line"
    done
    
    return 0
}

cc() {
    local provider=""
    local args=()
    
    if [[ $# -gt 0 && "$1" != --* ]]; then
        provider="$1"
        shift
    fi
    
    args=("$@")
    
    if [[ -z "$provider" ]]; then
        _ccwrap_load_config
        provider="$CURRENT_PROVIDER"
    fi
    
    if [[ -n "$provider" && "$provider" != "none" ]]; then
        if _ccwrap_load_provider_config "$provider"; then
            command claude "${args[@]}"
        else
            echo -e "\033[0;31mError:\033[0m Provider '$provider' not configured."
            echo "Run 'mcm add $provider' to add it."
            return 1
        fi
    else
        command claude "${args[@]}"
    fi
}
